AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  p2
  Sample SAM Template for p2

Globals:
  Function:
    Timeout: 3

Resources:
  hw2p2Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hw2p2Function
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7

Outputs:
  hw2p2Function:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt hw2p2Function.Arn
  hw2p2FunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt hw2p2FunctionRole.Arn